# **4. 인덱싱과 슬라이싱**

- 인덱스: 여러 원소를 가지고 있는 객체(리스트, 튜플, 배열 등)에 부여되는 번호
- 슬라이싱: 여러 원소를 가지고 있는 객체의 일부를 추출하는 것


---


- 파이썬의 List와 동일하게 ndarray도 인덱싱과 슬라이싱 사용 가능

In [1]:
import numpy as np

정리본

1. 

### 1) Indexing (인덱싱)

In [2]:
# 1부터 10까지 수 중 랜덤하게 6개의 수가 추출된 'arr1'이라는 배열
# shape: 3X2인 2차원 배열
arr1 = np.random.randint(1, 11, (3, 2))
arr1

array([[ 8, 10],
       [ 2,  4],
       [ 1,  8]])

In [3]:
# 1행 출력
arr1[0] # 행을 출력하는 것은 새로운 ndarray로 반환

array([ 8, 10])

In [4]:
# 2행 1열의 원소 출력
arr1[1][0] # 원소는 ndarray의 자료형에 맞게 반환

2

In [6]:
arr1[1, 0] # 중간에 ,를 사용하는 것으로도 인덱싱할 수 있다(row, column 순서)

2

### 2) Slicing (슬라이싱)

- 1차원 배열의 슬라이싱

In [7]:
# 10부터 19까지 연속적인 수로 이루어진 'arr2'라는 배열
# shape: 1차원 배열
arr2 = np.arange(10, 20, 1)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [8]:
# index가 4부터 6까지인 원소 출력
arr2[4:7]

array([14, 15, 16])

In [9]:
# index가 6 이상인 원소 출력
arr2[6:]

array([16, 17, 18, 19])

In [10]:
# index가 6 이상인 원소를 모두 20으로 바꾸기
arr2[6:] = 20 # 슬라이싱 하여 해당 부분을 가져오고 20을 대입하여 리스트의 원소를 변화시키는 방식
arr2

array([10, 11, 12, 13, 14, 15, 20, 20, 20, 20])

- 다차원 배열의 슬라이싱

In [11]:
# 1부터 9까지 연속적인 수로 이루어진 'arr3'라는 배열
# shape: 3X3인 2차원 배열
arr3 = np.arange(1, 10).reshape(3, 3)
arr3

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
# 2, 3, 5, 6으로 구성된 2차원 배열 출력
arr3[:2, 1:] # 콤마(,)를 이용하여 앞에는 row를, 뒤에는 column을 슬라이싱하였다
# arr3[:2] # 행을 기준으로 0부터 1(2미만)까지를 슬라이싱

array([[2, 3],
       [5, 6]])

In [19]:
# 1행과 2행 출력
arr3[:2, :] #row는 시작(0)부터 1(2미만)까지 슬라이싱, column은 전체
            #arr3[:2]와 동일한 출력

array([[1, 2, 3],
       [4, 5, 6]])

In [22]:
# 2열 출력
print(arr3[:, 1:2]) # 기존 arr3의 구조를 유지하면서 원하는 열(column)을 출력
print()
print(arr3[:, 1])   # 기존 arr3의 구조를 무시하고 1차원 배열로 원했던 열(column)의 원소들을 출력

[[2]
 [5]
 [8]]

[2 5 8]


In [23]:
# 2, 3, 5, 6을 모두 결측치로 바꾸기
# 결측치: 데이터에 값이 없는 것 (NaN, null, None)
# 결측치 != 0, False
arr3[:2, 1:] = np.nan

# 오류가 발생하는 이유는 nan은 기존 원소의 자료형이 float일 때만 변환시킬 수 있기 때문이다

ValueError: cannot convert float NaN to integer

In [24]:
# numpy에서 자료형이 float일 때만 결측치 삽입 가능
arr3 = arr3.astype('float64')
arr3[:2, 1:] = np.nan
arr3

array([[ 1., nan, nan],
       [ 4., nan, nan],
       [ 7.,  8.,  9.]])

### 3) 마스킹 연산 (boolean 인덱싱)

- 마스킹 연산: 조건에 부합하는 데이터만 추출하는 방법

In [26]:
# 난수가 표준정규분포 따르는 'arr4'라는 배열 생성
# shape: 5X5인 2차원 배열
arr4 = np.random.randn(5, 5)
arr4

array([[ 0.51321955, -1.08171034,  0.01671173, -0.31144897, -0.62580861],
       [-2.12342481, -0.73150296,  0.75523104,  0.39236703,  0.32208269],
       [ 0.8792229 ,  0.13566858, -0.86654452,  1.05276389,  0.73503426],
       [-0.02417307, -1.02628816,  1.48565166, -0.18021896, -0.22423662],
       [-0.65116128, -0.26367812,  2.47826164, -1.43624954, -0.29219381]])

In [27]:
# arr4 안의 원소가 양수이면 True, 음수이면 False 출력
arr4 > 0

array([[ True, False,  True, False, False],
       [False, False,  True,  True,  True],
       [ True,  True, False,  True,  True],
       [False, False,  True, False, False],
       [False, False,  True, False, False]])

In [29]:
# arr4 안의 원소가 음수면 0 삽입
arr4[arr4 < 0] = 0 #ndarray의 인덱스에 조건을 넣어주면 조건이 true가 되는 원소만 인덱싱할 수 있다
arr4


array([[0.51321955, 0.        , 0.01671173, 0.        , 0.        ],
       [0.        , 0.        , 0.75523104, 0.39236703, 0.32208269],
       [0.8792229 , 0.13566858, 0.        , 1.05276389, 0.73503426],
       [0.        , 0.        , 1.48565166, 0.        , 0.        ],
       [0.        , 0.        , 2.47826164, 0.        , 0.        ]])